name: mille
description: Showcase App for Windows UI for Flutter
version: 1.0.0+1
publish_to: "none"
environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.7.0"
dependencies:
  flutter:
    sdk: flutter
  fluent_ui: ^4.3.0
  provider: ^6.0.5
  system_theme: ^2.1.0
  window_manager: ^0.3.0
  flutter_acrylic: ^1.0.0+2
  url_strategy: ^0.2.0
  flutter_tabler_icons: ^1.1.2
  url_launcher: ^6.1.7
  clipboard: ^0.1.3
  email_validator: ^2.1.17
  http: ^0.13.5
  flutter_markdown: ^0.6.13
  flutter_syntax_view:
    git:
      url: https://github.com/YehudaKremer/flutter_syntax_view.git
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  go_router: ^6.5.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.1.6
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.11.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  # generate: true
  #
flutter_native_splash:
  color: "#000000"
  image: assets/logo.png
flutter_icons:
  # android: false
  # ios: false
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "202020"
    theme_color: "0175C2"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo.png"
