// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.79.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import 'bridge_generated.io.dart'
    if (dart.library.html) 'bridge_generated.web.dart';
import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';

abstract class Native {
  /// Returns the current platform
  ///
  /// # Returns
  ///
  /// [Platform] enum representing the current runtime environment.
  Future<Platform> platform({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kPlatformConstMeta;

  /// Returns whether the current runtime is in debug mode or not
  ///
  /// # Returns
  ///
  /// `true` if the current runtime is in debug mode, `false` otherwise.
  Future<bool> rustReleaseMode({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kRustReleaseModeConstMeta;

  /// Adds two integers
  Future<int> add({required int a, required int b, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kAddConstMeta;

  /// Divides two integers
  Future<int> divide({required int a, required int b, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kDivideConstMeta;
}

/// Represents the current rutime platform.
enum Platform {
  /// Current runtime environment is Android
  /// (or ChromeOS, FireOS, etc.)
  Android,

  /// Current runtime environment is iOS
  /// (or iPadOS, watchOS, tvOS)
  Ios,

  /// Current runtime environment is Windows
  /// (including UWP)
  Windows,

  /// Current runtime environment is Unix
  /// (Linux, BSD, MacOS, etc.)
  Unix,

  /// Current runtime environment is MacOS
  Macos,

  /// Current runtime environment is WebAssembly
  /// (or any other Wasm-based environment)
  Wasm,

  /// Current runtime environment could not be determined
  /// (or is not supported)
  Unknown,
}
